using UnityEngine;

namespace Code.Deprecated
{
    public class Thrusters : MonoBehaviour
    {
        public ThrusterConfiguration ThrusterConfiguration;
    
        // Update is called once per frame
        private void FixedUpdate()
        {
            if (Input.anyKey)
            {
                if (Input.GetKey(KeyCode.A)) MoveLeft(ThrusterConfiguration.LeftThrust);
                if (Input.GetKey(KeyCode.D)) MoveRight(ThrusterConfiguration.RightThrust);
                if (Input.GetKey(KeyCode.W)) MoveForward(ThrusterConfiguration.ForwardThrust);
                if (Input.GetKey(KeyCode.S)) MoveBackward(ThrusterConfiguration.BackwardThrust);
                if (Input.GetKey(KeyCode.Space)) MoveUp(ThrusterConfiguration.UpThrust);
                if (Input.GetKey(KeyCode.C))  MoveDown(ThrusterConfiguration.DownThrust);
            
                if (Input.GetKey(KeyCode.LeftArrow)) YawLeft(ThrusterConfiguration.LeftThrust + ThrusterConfiguration.RightThrust / 4);
                if (Input.GetKey(KeyCode.RightArrow)) YawRight(ThrusterConfiguration.LeftThrust + ThrusterConfiguration.RightThrust / 4);
                if (Input.GetKey(KeyCode.UpArrow)) PitchDown(ThrusterConfiguration.UpThrust + ThrusterConfiguration.DownThrust / 4);
                if (Input.GetKey(KeyCode.DownArrow)) PitchUp(ThrusterConfiguration.UpThrust + ThrusterConfiguration.DownThrust / 4);
                if (Input.GetKey(KeyCode.Q)) RollLeft(ThrusterConfiguration.LeftThrust + ThrusterConfiguration.RightThrust / 4);
                if (Input.GetKey(KeyCode.E)) RollRight(ThrusterConfiguration.LeftThrust + ThrusterConfiguration.RightThrust / 4);
            }
        }

        private void MoveLeft(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeForce(Vector3.left * multiplier);
        private void MoveRight(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeForce(Vector3.right * multiplier);
        private void MoveForward(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeForce(Vector3.forward * multiplier);
        private void MoveBackward(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeForce(Vector3.back * multiplier);
        private void MoveUp(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeForce(Vector3.up * multiplier);
        private void MoveDown(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeForce(Vector3.down * multiplier);
    
        private void PitchDown(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeTorque(Vector3.right * multiplier);
        private void PitchUp(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeTorque(Vector3.left * multiplier);
        private void YawLeft(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeTorque(Vector3.down * multiplier);
        private void YawRight(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeTorque(Vector3.up * multiplier);
        private void RollLeft(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeTorque(Vector3.forward * multiplier);
        private void RollRight(float multiplier = 1000) => gameObject.GetComponent<Rigidbody>().AddRelativeTorque(Vector3.back * multiplier);

        private KeyCode GetKeyCode()
        {
            if (Input.GetKey(KeyCode.Backspace)) return KeyCode.Backspace;
            if (Input.GetKey(KeyCode.Tab)) return KeyCode.Tab;
            if (Input.GetKey(KeyCode.Clear)) return KeyCode.Clear;
            if (Input.GetKey(KeyCode.Return)) return KeyCode.Return;
            if (Input.GetKey(KeyCode.Pause)) return KeyCode.Pause;
            if (Input.GetKey(KeyCode.Escape)) return KeyCode.Escape;
            if (Input.GetKey(KeyCode.Space)) return KeyCode.Space;
            if (Input.GetKey(KeyCode.Exclaim)) return KeyCode.Exclaim;
            if (Input.GetKey(KeyCode.DoubleQuote)) return KeyCode.DoubleQuote;
            if (Input.GetKey(KeyCode.Hash)) return KeyCode.Hash;
            if (Input.GetKey(KeyCode.Dollar)) return KeyCode.Dollar;
            if (Input.GetKey(KeyCode.Percent)) return KeyCode.Percent;
            if (Input.GetKey(KeyCode.Ampersand)) return KeyCode.Ampersand;
            if (Input.GetKey(KeyCode.Quote)) return KeyCode.Quote;
            if (Input.GetKey(KeyCode.LeftParen)) return KeyCode.LeftParen;
            if (Input.GetKey(KeyCode.RightParen)) return KeyCode.RightParen;
            if (Input.GetKey(KeyCode.Asterisk)) return KeyCode.Asterisk;
            if (Input.GetKey(KeyCode.Plus)) return KeyCode.Plus;
            if (Input.GetKey(KeyCode.Comma)) return KeyCode.Comma;
            if (Input.GetKey(KeyCode.Minus)) return KeyCode.Minus;
            if (Input.GetKey(KeyCode.Period)) return KeyCode.Period;
            if (Input.GetKey(KeyCode.Slash)) return KeyCode.Slash;
            if (Input.GetKey(KeyCode.Alpha0)) return KeyCode.Alpha0;
            if (Input.GetKey(KeyCode.Alpha1)) return KeyCode.Alpha1;
            if (Input.GetKey(KeyCode.Alpha2)) return KeyCode.Alpha2;
            if (Input.GetKey(KeyCode.Alpha3)) return KeyCode.Alpha3;
            if (Input.GetKey(KeyCode.Alpha4)) return KeyCode.Alpha4;
            if (Input.GetKey(KeyCode.Alpha5)) return KeyCode.Alpha5;
            if (Input.GetKey(KeyCode.Alpha6)) return KeyCode.Alpha6;
            if (Input.GetKey(KeyCode.Alpha7)) return KeyCode.Alpha7;
            if (Input.GetKey(KeyCode.Alpha8)) return KeyCode.Alpha8;
            if (Input.GetKey(KeyCode.Alpha9)) return KeyCode.Alpha9;
            if (Input.GetKey(KeyCode.Colon)) return KeyCode.Colon;
            if (Input.GetKey(KeyCode.Semicolon)) return KeyCode.Semicolon;
            if (Input.GetKey(KeyCode.Less)) return KeyCode.Less;
            if (Input.GetKey(KeyCode.Equals)) return KeyCode.Equals;
            if (Input.GetKey(KeyCode.Greater)) return KeyCode.Greater;
            if (Input.GetKey(KeyCode.Question)) return KeyCode.Question;
            if (Input.GetKey(KeyCode.At)) return KeyCode.At;
            if (Input.GetKey(KeyCode.LeftBracket)) return KeyCode.LeftBracket;
            if (Input.GetKey(KeyCode.Backslash)) return KeyCode.Backslash;
            if (Input.GetKey(KeyCode.RightBracket)) return KeyCode.RightBracket;
            if (Input.GetKey(KeyCode.Caret)) return KeyCode.Caret;
            if (Input.GetKey(KeyCode.Underscore)) return KeyCode.Underscore;
            if (Input.GetKey(KeyCode.BackQuote)) return KeyCode.BackQuote;
            if (Input.GetKey(KeyCode.A)) return KeyCode.A;
            if (Input.GetKey(KeyCode.B)) return KeyCode.B;
            if (Input.GetKey(KeyCode.C)) return KeyCode.C;
            if (Input.GetKey(KeyCode.D)) return KeyCode.D;
            if (Input.GetKey(KeyCode.E)) return KeyCode.E;
            if (Input.GetKey(KeyCode.F)) return KeyCode.F;
            if (Input.GetKey(KeyCode.G)) return KeyCode.G;
            if (Input.GetKey(KeyCode.H)) return KeyCode.H;
            if (Input.GetKey(KeyCode.I)) return KeyCode.I;
            if (Input.GetKey(KeyCode.J)) return KeyCode.J;
            if (Input.GetKey(KeyCode.K)) return KeyCode.K;
            if (Input.GetKey(KeyCode.L)) return KeyCode.L;
            if (Input.GetKey(KeyCode.M)) return KeyCode.M;
            if (Input.GetKey(KeyCode.N)) return KeyCode.N;
            if (Input.GetKey(KeyCode.O)) return KeyCode.O;
            if (Input.GetKey(KeyCode.P)) return KeyCode.P;
            if (Input.GetKey(KeyCode.Q)) return KeyCode.Q;
            if (Input.GetKey(KeyCode.R)) return KeyCode.R;
            if (Input.GetKey(KeyCode.S)) return KeyCode.S;
            if (Input.GetKey(KeyCode.T)) return KeyCode.T;
            if (Input.GetKey(KeyCode.U)) return KeyCode.U;
            if (Input.GetKey(KeyCode.V)) return KeyCode.V;
            if (Input.GetKey(KeyCode.W)) return KeyCode.W;
            if (Input.GetKey(KeyCode.X)) return KeyCode.X;
            if (Input.GetKey(KeyCode.Y)) return KeyCode.Y;
            if (Input.GetKey(KeyCode.Z)) return KeyCode.Z;
            if (Input.GetKey(KeyCode.LeftCurlyBracket)) return KeyCode.LeftCurlyBracket;
            if (Input.GetKey(KeyCode.Pipe)) return KeyCode.Pipe;
            if (Input.GetKey(KeyCode.RightCurlyBracket)) return KeyCode.RightCurlyBracket;
            if (Input.GetKey(KeyCode.Tilde)) return KeyCode.Tilde;
            if (Input.GetKey(KeyCode.Delete)) return KeyCode.Delete;
            if (Input.GetKey(KeyCode.Keypad0)) return KeyCode.Keypad0;
            if (Input.GetKey(KeyCode.Keypad1)) return KeyCode.Keypad1;
            if (Input.GetKey(KeyCode.Keypad2)) return KeyCode.Keypad2;
            if (Input.GetKey(KeyCode.Keypad3)) return KeyCode.Keypad3;
            if (Input.GetKey(KeyCode.Keypad4)) return KeyCode.Keypad4;
            if (Input.GetKey(KeyCode.Keypad5)) return KeyCode.Keypad5;
            if (Input.GetKey(KeyCode.Keypad6)) return KeyCode.Keypad6;
            if (Input.GetKey(KeyCode.Keypad7)) return KeyCode.Keypad7;
            if (Input.GetKey(KeyCode.Keypad8)) return KeyCode.Keypad8;
            if (Input.GetKey(KeyCode.Keypad9)) return KeyCode.Keypad9;
            if (Input.GetKey(KeyCode.KeypadPeriod)) return KeyCode.KeypadPeriod;
            if (Input.GetKey(KeyCode.KeypadDivide)) return KeyCode.KeypadDivide;
            if (Input.GetKey(KeyCode.KeypadMultiply)) return KeyCode.KeypadMultiply;
            if (Input.GetKey(KeyCode.KeypadMinus)) return KeyCode.KeypadMinus;
            if (Input.GetKey(KeyCode.KeypadPlus)) return KeyCode.KeypadPlus;
            if (Input.GetKey(KeyCode.KeypadEnter)) return KeyCode.KeypadEnter;
            if (Input.GetKey(KeyCode.KeypadEquals)) return KeyCode.KeypadEquals;
            if (Input.GetKey(KeyCode.UpArrow)) return KeyCode.UpArrow;
            if (Input.GetKey(KeyCode.DownArrow)) return KeyCode.DownArrow;
            if (Input.GetKey(KeyCode.RightArrow)) return KeyCode.RightArrow;
            if (Input.GetKey(KeyCode.LeftArrow)) return KeyCode.LeftArrow;
            if (Input.GetKey(KeyCode.Insert)) return KeyCode.Insert;
            if (Input.GetKey(KeyCode.Home)) return KeyCode.Home;
            if (Input.GetKey(KeyCode.End)) return KeyCode.End;
            if (Input.GetKey(KeyCode.PageUp)) return KeyCode.PageUp;
            if (Input.GetKey(KeyCode.PageDown)) return KeyCode.PageDown;
            if (Input.GetKey(KeyCode.F1)) return KeyCode.F1;
            if (Input.GetKey(KeyCode.F2)) return KeyCode.F2;
            if (Input.GetKey(KeyCode.F3)) return KeyCode.F3;
            if (Input.GetKey(KeyCode.F4)) return KeyCode.F4;
            if (Input.GetKey(KeyCode.F5)) return KeyCode.F5;
            if (Input.GetKey(KeyCode.F6)) return KeyCode.F6;
            if (Input.GetKey(KeyCode.F7)) return KeyCode.F7;
            if (Input.GetKey(KeyCode.F8)) return KeyCode.F8;
            if (Input.GetKey(KeyCode.F9)) return KeyCode.F9;
            if (Input.GetKey(KeyCode.F10)) return KeyCode.F10;
            if (Input.GetKey(KeyCode.F11)) return KeyCode.F11;
            if (Input.GetKey(KeyCode.F12)) return KeyCode.F12;
            if (Input.GetKey(KeyCode.F13)) return KeyCode.F13;
            if (Input.GetKey(KeyCode.F14)) return KeyCode.F14;
            if (Input.GetKey(KeyCode.F15)) return KeyCode.F15;
            if (Input.GetKey(KeyCode.Numlock)) return KeyCode.Numlock;
            if (Input.GetKey(KeyCode.CapsLock)) return KeyCode.CapsLock;
            if (Input.GetKey(KeyCode.ScrollLock)) return KeyCode.ScrollLock;
            if (Input.GetKey(KeyCode.RightShift)) return KeyCode.RightShift;
            if (Input.GetKey(KeyCode.LeftShift)) return KeyCode.LeftShift;
            if (Input.GetKey(KeyCode.RightControl)) return KeyCode.RightControl;
            if (Input.GetKey(KeyCode.LeftControl)) return KeyCode.LeftControl;
            if (Input.GetKey(KeyCode.RightAlt)) return KeyCode.RightAlt;
            if (Input.GetKey(KeyCode.LeftAlt)) return KeyCode.LeftAlt;
            if (Input.GetKey(KeyCode.RightCommand)) return KeyCode.RightCommand;
            if (Input.GetKey(KeyCode.RightApple)) return KeyCode.RightApple;
            if (Input.GetKey(KeyCode.LeftCommand)) return KeyCode.LeftCommand;
            if (Input.GetKey(KeyCode.LeftApple)) return KeyCode.LeftApple;
            if (Input.GetKey(KeyCode.LeftWindows)) return KeyCode.LeftWindows;
            if (Input.GetKey(KeyCode.RightWindows)) return KeyCode.RightWindows;
            if (Input.GetKey(KeyCode.AltGr)) return KeyCode.AltGr;
            if (Input.GetKey(KeyCode.Help)) return KeyCode.Help;
            if (Input.GetKey(KeyCode.Print)) return KeyCode.Print;
            if (Input.GetKey(KeyCode.SysReq)) return KeyCode.SysReq;
            if (Input.GetKey(KeyCode.Break)) return KeyCode.Break;
            if (Input.GetKey(KeyCode.Menu)) return KeyCode.Menu;
            if (Input.GetKey(KeyCode.Mouse0)) return KeyCode.Mouse0;
            if (Input.GetKey(KeyCode.Mouse1)) return KeyCode.Mouse1;
            if (Input.GetKey(KeyCode.Mouse2)) return KeyCode.Mouse2;
            if (Input.GetKey(KeyCode.Mouse3)) return KeyCode.Mouse3;
            if (Input.GetKey(KeyCode.Mouse4)) return KeyCode.Mouse4;
            if (Input.GetKey(KeyCode.Mouse5)) return KeyCode.Mouse5;
            if (Input.GetKey(KeyCode.Mouse6)) return KeyCode.Mouse6;
            if (Input.GetKey(KeyCode.JoystickButton0)) return KeyCode.JoystickButton0;
            if (Input.GetKey(KeyCode.JoystickButton1)) return KeyCode.JoystickButton1;
            if (Input.GetKey(KeyCode.JoystickButton2)) return KeyCode.JoystickButton2;
            if (Input.GetKey(KeyCode.JoystickButton3)) return KeyCode.JoystickButton3;
            if (Input.GetKey(KeyCode.JoystickButton4)) return KeyCode.JoystickButton4;
            if (Input.GetKey(KeyCode.JoystickButton5)) return KeyCode.JoystickButton5;
            if (Input.GetKey(KeyCode.JoystickButton6)) return KeyCode.JoystickButton6;
            if (Input.GetKey(KeyCode.JoystickButton7)) return KeyCode.JoystickButton7;
            if (Input.GetKey(KeyCode.JoystickButton8)) return KeyCode.JoystickButton8;
            if (Input.GetKey(KeyCode.JoystickButton9)) return KeyCode.JoystickButton9;
            if (Input.GetKey(KeyCode.JoystickButton10)) return KeyCode.JoystickButton10;
            if (Input.GetKey(KeyCode.JoystickButton11)) return KeyCode.JoystickButton11;
            if (Input.GetKey(KeyCode.JoystickButton12)) return KeyCode.JoystickButton12;
            if (Input.GetKey(KeyCode.JoystickButton13)) return KeyCode.JoystickButton13;
            if (Input.GetKey(KeyCode.JoystickButton14)) return KeyCode.JoystickButton14;
            if (Input.GetKey(KeyCode.JoystickButton15)) return KeyCode.JoystickButton15;
            if (Input.GetKey(KeyCode.JoystickButton16)) return KeyCode.JoystickButton16;
            if (Input.GetKey(KeyCode.JoystickButton17)) return KeyCode.JoystickButton17;
            if (Input.GetKey(KeyCode.JoystickButton18)) return KeyCode.JoystickButton18;
            if (Input.GetKey(KeyCode.JoystickButton19)) return KeyCode.JoystickButton19;
            if (Input.GetKey(KeyCode.Joystick1Button0)) return KeyCode.Joystick1Button0;
            if (Input.GetKey(KeyCode.Joystick1Button1)) return KeyCode.Joystick1Button1;
            if (Input.GetKey(KeyCode.Joystick1Button2)) return KeyCode.Joystick1Button2;
            if (Input.GetKey(KeyCode.Joystick1Button3)) return KeyCode.Joystick1Button3;
            if (Input.GetKey(KeyCode.Joystick1Button4)) return KeyCode.Joystick1Button4;
            if (Input.GetKey(KeyCode.Joystick1Button5)) return KeyCode.Joystick1Button5;
            if (Input.GetKey(KeyCode.Joystick1Button6)) return KeyCode.Joystick1Button6;
            if (Input.GetKey(KeyCode.Joystick1Button7)) return KeyCode.Joystick1Button7;
            if (Input.GetKey(KeyCode.Joystick1Button8)) return KeyCode.Joystick1Button8;
            if (Input.GetKey(KeyCode.Joystick1Button9)) return KeyCode.Joystick1Button9;
            if (Input.GetKey(KeyCode.Joystick1Button10)) return KeyCode.Joystick1Button10;
            if (Input.GetKey(KeyCode.Joystick1Button11)) return KeyCode.Joystick1Button11;
            if (Input.GetKey(KeyCode.Joystick1Button12)) return KeyCode.Joystick1Button12;
            if (Input.GetKey(KeyCode.Joystick1Button13)) return KeyCode.Joystick1Button13;
            if (Input.GetKey(KeyCode.Joystick1Button14)) return KeyCode.Joystick1Button14;
            if (Input.GetKey(KeyCode.Joystick1Button15)) return KeyCode.Joystick1Button15;
            if (Input.GetKey(KeyCode.Joystick1Button16)) return KeyCode.Joystick1Button16;
            if (Input.GetKey(KeyCode.Joystick1Button17)) return KeyCode.Joystick1Button17;
            if (Input.GetKey(KeyCode.Joystick1Button18)) return KeyCode.Joystick1Button18;
            if (Input.GetKey(KeyCode.Joystick1Button19)) return KeyCode.Joystick1Button19;
            if (Input.GetKey(KeyCode.Joystick2Button0)) return KeyCode.Joystick2Button0;
            if (Input.GetKey(KeyCode.Joystick2Button1)) return KeyCode.Joystick2Button1;
            if (Input.GetKey(KeyCode.Joystick2Button2)) return KeyCode.Joystick2Button2;
            if (Input.GetKey(KeyCode.Joystick2Button3)) return KeyCode.Joystick2Button3;
            if (Input.GetKey(KeyCode.Joystick2Button4)) return KeyCode.Joystick2Button4;
            if (Input.GetKey(KeyCode.Joystick2Button5)) return KeyCode.Joystick2Button5;
            if (Input.GetKey(KeyCode.Joystick2Button6)) return KeyCode.Joystick2Button6;
            if (Input.GetKey(KeyCode.Joystick2Button7)) return KeyCode.Joystick2Button7;
            if (Input.GetKey(KeyCode.Joystick2Button8)) return KeyCode.Joystick2Button8;
            if (Input.GetKey(KeyCode.Joystick2Button9)) return KeyCode.Joystick2Button9;
            if (Input.GetKey(KeyCode.Joystick2Button10)) return KeyCode.Joystick2Button10;
            if (Input.GetKey(KeyCode.Joystick2Button11)) return KeyCode.Joystick2Button11;
            if (Input.GetKey(KeyCode.Joystick2Button12)) return KeyCode.Joystick2Button12;
            if (Input.GetKey(KeyCode.Joystick2Button13)) return KeyCode.Joystick2Button13;
            if (Input.GetKey(KeyCode.Joystick2Button14)) return KeyCode.Joystick2Button14;
            if (Input.GetKey(KeyCode.Joystick2Button15)) return KeyCode.Joystick2Button15;
            if (Input.GetKey(KeyCode.Joystick2Button16)) return KeyCode.Joystick2Button16;
            if (Input.GetKey(KeyCode.Joystick2Button17)) return KeyCode.Joystick2Button17;
            if (Input.GetKey(KeyCode.Joystick2Button18)) return KeyCode.Joystick2Button18;
            if (Input.GetKey(KeyCode.Joystick2Button19)) return KeyCode.Joystick2Button19;
            if (Input.GetKey(KeyCode.Joystick3Button0)) return KeyCode.Joystick3Button0;
            if (Input.GetKey(KeyCode.Joystick3Button1)) return KeyCode.Joystick3Button1;
            if (Input.GetKey(KeyCode.Joystick3Button2)) return KeyCode.Joystick3Button2;
            if (Input.GetKey(KeyCode.Joystick3Button3)) return KeyCode.Joystick3Button3;
            if (Input.GetKey(KeyCode.Joystick3Button4)) return KeyCode.Joystick3Button4;
            if (Input.GetKey(KeyCode.Joystick3Button5)) return KeyCode.Joystick3Button5;
            if (Input.GetKey(KeyCode.Joystick3Button6)) return KeyCode.Joystick3Button6;
            if (Input.GetKey(KeyCode.Joystick3Button7)) return KeyCode.Joystick3Button7;
            if (Input.GetKey(KeyCode.Joystick3Button8)) return KeyCode.Joystick3Button8;
            if (Input.GetKey(KeyCode.Joystick3Button9)) return KeyCode.Joystick3Button9;
            if (Input.GetKey(KeyCode.Joystick3Button10)) return KeyCode.Joystick3Button10;
            if (Input.GetKey(KeyCode.Joystick3Button11)) return KeyCode.Joystick3Button11;
            if (Input.GetKey(KeyCode.Joystick3Button12)) return KeyCode.Joystick3Button12;
            if (Input.GetKey(KeyCode.Joystick3Button13)) return KeyCode.Joystick3Button13;
            if (Input.GetKey(KeyCode.Joystick3Button14)) return KeyCode.Joystick3Button14;
            if (Input.GetKey(KeyCode.Joystick3Button15)) return KeyCode.Joystick3Button15;
            if (Input.GetKey(KeyCode.Joystick3Button16)) return KeyCode.Joystick3Button16;
            if (Input.GetKey(KeyCode.Joystick3Button17)) return KeyCode.Joystick3Button17;
            if (Input.GetKey(KeyCode.Joystick3Button18)) return KeyCode.Joystick3Button18;
            if (Input.GetKey(KeyCode.Joystick3Button19)) return KeyCode.Joystick3Button19;
            if (Input.GetKey(KeyCode.Joystick4Button0)) return KeyCode.Joystick4Button0;
            if (Input.GetKey(KeyCode.Joystick4Button1)) return KeyCode.Joystick4Button1;
            if (Input.GetKey(KeyCode.Joystick4Button2)) return KeyCode.Joystick4Button2;
            if (Input.GetKey(KeyCode.Joystick4Button3)) return KeyCode.Joystick4Button3;
            if (Input.GetKey(KeyCode.Joystick4Button4)) return KeyCode.Joystick4Button4;
            if (Input.GetKey(KeyCode.Joystick4Button5)) return KeyCode.Joystick4Button5;
            if (Input.GetKey(KeyCode.Joystick4Button6)) return KeyCode.Joystick4Button6;
            if (Input.GetKey(KeyCode.Joystick4Button7)) return KeyCode.Joystick4Button7;
            if (Input.GetKey(KeyCode.Joystick4Button8)) return KeyCode.Joystick4Button8;
            if (Input.GetKey(KeyCode.Joystick4Button9)) return KeyCode.Joystick4Button9;
            if (Input.GetKey(KeyCode.Joystick4Button10)) return KeyCode.Joystick4Button10;
            if (Input.GetKey(KeyCode.Joystick4Button11)) return KeyCode.Joystick4Button11;
            if (Input.GetKey(KeyCode.Joystick4Button12)) return KeyCode.Joystick4Button12;
            if (Input.GetKey(KeyCode.Joystick4Button13)) return KeyCode.Joystick4Button13;
            if (Input.GetKey(KeyCode.Joystick4Button14)) return KeyCode.Joystick4Button14;
            if (Input.GetKey(KeyCode.Joystick4Button15)) return KeyCode.Joystick4Button15;
            if (Input.GetKey(KeyCode.Joystick4Button16)) return KeyCode.Joystick4Button16;
            if (Input.GetKey(KeyCode.Joystick4Button17)) return KeyCode.Joystick4Button17;
            if (Input.GetKey(KeyCode.Joystick4Button18)) return KeyCode.Joystick4Button18;
            if (Input.GetKey(KeyCode.Joystick4Button19)) return KeyCode.Joystick4Button19;
            if (Input.GetKey(KeyCode.Joystick5Button0)) return KeyCode.Joystick5Button0;
            if (Input.GetKey(KeyCode.Joystick5Button1)) return KeyCode.Joystick5Button1;
            if (Input.GetKey(KeyCode.Joystick5Button2)) return KeyCode.Joystick5Button2;
            if (Input.GetKey(KeyCode.Joystick5Button3)) return KeyCode.Joystick5Button3;
            if (Input.GetKey(KeyCode.Joystick5Button4)) return KeyCode.Joystick5Button4;
            if (Input.GetKey(KeyCode.Joystick5Button5)) return KeyCode.Joystick5Button5;
            if (Input.GetKey(KeyCode.Joystick5Button6)) return KeyCode.Joystick5Button6;
            if (Input.GetKey(KeyCode.Joystick5Button7)) return KeyCode.Joystick5Button7;
            if (Input.GetKey(KeyCode.Joystick5Button8)) return KeyCode.Joystick5Button8;
            if (Input.GetKey(KeyCode.Joystick5Button9)) return KeyCode.Joystick5Button9;
            if (Input.GetKey(KeyCode.Joystick5Button10)) return KeyCode.Joystick5Button10;
            if (Input.GetKey(KeyCode.Joystick5Button11)) return KeyCode.Joystick5Button11;
            if (Input.GetKey(KeyCode.Joystick5Button12)) return KeyCode.Joystick5Button12;
            if (Input.GetKey(KeyCode.Joystick5Button13)) return KeyCode.Joystick5Button13;
            if (Input.GetKey(KeyCode.Joystick5Button14)) return KeyCode.Joystick5Button14;
            if (Input.GetKey(KeyCode.Joystick5Button15)) return KeyCode.Joystick5Button15;
            if (Input.GetKey(KeyCode.Joystick5Button16)) return KeyCode.Joystick5Button16;
            if (Input.GetKey(KeyCode.Joystick5Button17)) return KeyCode.Joystick5Button17;
            if (Input.GetKey(KeyCode.Joystick5Button18)) return KeyCode.Joystick5Button18;
            if (Input.GetKey(KeyCode.Joystick5Button19)) return KeyCode.Joystick5Button19;
            if (Input.GetKey(KeyCode.Joystick6Button0)) return KeyCode.Joystick6Button0;
            if (Input.GetKey(KeyCode.Joystick6Button1)) return KeyCode.Joystick6Button1;
            if (Input.GetKey(KeyCode.Joystick6Button2)) return KeyCode.Joystick6Button2;
            if (Input.GetKey(KeyCode.Joystick6Button3)) return KeyCode.Joystick6Button3;
            if (Input.GetKey(KeyCode.Joystick6Button4)) return KeyCode.Joystick6Button4;
            if (Input.GetKey(KeyCode.Joystick6Button5)) return KeyCode.Joystick6Button5;
            if (Input.GetKey(KeyCode.Joystick6Button6)) return KeyCode.Joystick6Button6;
            if (Input.GetKey(KeyCode.Joystick6Button7)) return KeyCode.Joystick6Button7;
            if (Input.GetKey(KeyCode.Joystick6Button8)) return KeyCode.Joystick6Button8;
            if (Input.GetKey(KeyCode.Joystick6Button9)) return KeyCode.Joystick6Button9;
            if (Input.GetKey(KeyCode.Joystick6Button10)) return KeyCode.Joystick6Button10;
            if (Input.GetKey(KeyCode.Joystick6Button11)) return KeyCode.Joystick6Button11;
            if (Input.GetKey(KeyCode.Joystick6Button12)) return KeyCode.Joystick6Button12;
            if (Input.GetKey(KeyCode.Joystick6Button13)) return KeyCode.Joystick6Button13;
            if (Input.GetKey(KeyCode.Joystick6Button14)) return KeyCode.Joystick6Button14;
            if (Input.GetKey(KeyCode.Joystick6Button15)) return KeyCode.Joystick6Button15;
            if (Input.GetKey(KeyCode.Joystick6Button16)) return KeyCode.Joystick6Button16;
            if (Input.GetKey(KeyCode.Joystick6Button17)) return KeyCode.Joystick6Button17;
            if (Input.GetKey(KeyCode.Joystick6Button18)) return KeyCode.Joystick6Button18;
            if (Input.GetKey(KeyCode.Joystick6Button19)) return KeyCode.Joystick6Button19;
            if (Input.GetKey(KeyCode.Joystick7Button0)) return KeyCode.Joystick7Button0;
            if (Input.GetKey(KeyCode.Joystick7Button1)) return KeyCode.Joystick7Button1;
            if (Input.GetKey(KeyCode.Joystick7Button2)) return KeyCode.Joystick7Button2;
            if (Input.GetKey(KeyCode.Joystick7Button3)) return KeyCode.Joystick7Button3;
            if (Input.GetKey(KeyCode.Joystick7Button4)) return KeyCode.Joystick7Button4;
            if (Input.GetKey(KeyCode.Joystick7Button5)) return KeyCode.Joystick7Button5;
            if (Input.GetKey(KeyCode.Joystick7Button6)) return KeyCode.Joystick7Button6;
            if (Input.GetKey(KeyCode.Joystick7Button7)) return KeyCode.Joystick7Button7;
            if (Input.GetKey(KeyCode.Joystick7Button8)) return KeyCode.Joystick7Button8;
            if (Input.GetKey(KeyCode.Joystick7Button9)) return KeyCode.Joystick7Button9;
            if (Input.GetKey(KeyCode.Joystick7Button10)) return KeyCode.Joystick7Button10;
            if (Input.GetKey(KeyCode.Joystick7Button11)) return KeyCode.Joystick7Button11;
            if (Input.GetKey(KeyCode.Joystick7Button12)) return KeyCode.Joystick7Button12;
            if (Input.GetKey(KeyCode.Joystick7Button13)) return KeyCode.Joystick7Button13;
            if (Input.GetKey(KeyCode.Joystick7Button14)) return KeyCode.Joystick7Button14;
            if (Input.GetKey(KeyCode.Joystick7Button15)) return KeyCode.Joystick7Button15;
            if (Input.GetKey(KeyCode.Joystick7Button16)) return KeyCode.Joystick7Button16;
            if (Input.GetKey(KeyCode.Joystick7Button17)) return KeyCode.Joystick7Button17;
            if (Input.GetKey(KeyCode.Joystick7Button18)) return KeyCode.Joystick7Button18;
            if (Input.GetKey(KeyCode.Joystick7Button19)) return KeyCode.Joystick7Button19;
            if (Input.GetKey(KeyCode.Joystick8Button0)) return KeyCode.Joystick8Button0;
            if (Input.GetKey(KeyCode.Joystick8Button1)) return KeyCode.Joystick8Button1;
            if (Input.GetKey(KeyCode.Joystick8Button2)) return KeyCode.Joystick8Button2;
            if (Input.GetKey(KeyCode.Joystick8Button3)) return KeyCode.Joystick8Button3;
            if (Input.GetKey(KeyCode.Joystick8Button4)) return KeyCode.Joystick8Button4;
            if (Input.GetKey(KeyCode.Joystick8Button5)) return KeyCode.Joystick8Button5;
            if (Input.GetKey(KeyCode.Joystick8Button6)) return KeyCode.Joystick8Button6;
            if (Input.GetKey(KeyCode.Joystick8Button7)) return KeyCode.Joystick8Button7;
            if (Input.GetKey(KeyCode.Joystick8Button8)) return KeyCode.Joystick8Button8;
            if (Input.GetKey(KeyCode.Joystick8Button9)) return KeyCode.Joystick8Button9;
            if (Input.GetKey(KeyCode.Joystick8Button10)) return KeyCode.Joystick8Button10;
            if (Input.GetKey(KeyCode.Joystick8Button11)) return KeyCode.Joystick8Button11;
            if (Input.GetKey(KeyCode.Joystick8Button12)) return KeyCode.Joystick8Button12;
            if (Input.GetKey(KeyCode.Joystick8Button13)) return KeyCode.Joystick8Button13;
            if (Input.GetKey(KeyCode.Joystick8Button14)) return KeyCode.Joystick8Button14;
            if (Input.GetKey(KeyCode.Joystick8Button15)) return KeyCode.Joystick8Button15;
            if (Input.GetKey(KeyCode.Joystick8Button16)) return KeyCode.Joystick8Button16;
            if (Input.GetKey(KeyCode.Joystick8Button17)) return KeyCode.Joystick8Button17;
            if (Input.GetKey(KeyCode.Joystick8Button18)) return KeyCode.Joystick8Button18;
            if (Input.GetKey(KeyCode.Joystick8Button19)) return KeyCode.Joystick8Button19;
        
            return KeyCode.None;
        }
    }
}
